### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by Abbyws** [thunlp/Adv-ED#1]
您好，我最近也在做事件抽取的工作，但是苦于没有数据集，请问可以发我一份吗？我的邮箱是：wangshuo@stu.xjtu.edu.cn。非常感谢！

**Comment by Bakser** [comment]
您好，我们的数据集是ACE2005（LDC2006T06），分发这份数据是违反LDC规定的，您可以在LDC上获得它（https://catalog.ldc.upenn.edu/LDC2006T06）。
