### ISSUE TITLE
Dscore_G参数写错了吧

### ISSUE THREAD

**Issue by Riroaki** [thunlp/Adv-ED#10]
https://github.com/thunlp/Adv-ED/blob/60bf9546c91558ca956a3957003a14166590a8f0/BERT/train.py#L128

这一行里面，根据Dscore_G函数的定义，输入参数应该是：
```python
dScores = Dscore_G(nwords, nMask, nmaskL, nmaskR, nlabel,
                       uwords, uMask, umaskL, umaskR, ulabel)
```
源代码中的npos,nloc和upos,uloc都没有找到定义

**Comment by Bakser** [comment]
您好，感谢提醒！这里应该是我们整理合并代码时出现了错误，会马上修复。
