### ISSUE TITLE
NA标签计算问题

### ISSUE THREAD

**Issue by hlee-top** [thunlp/Adv-ED#11]
作者您好，请问NA标签为什么使用平均数计算，不能当作一个新的标签计算吗？感谢您所做的工作！
![image](https://user-images.githubusercontent.com/49368187/124055783-1c7e9600-da57-11eb-821e-3e29639bc689.png)

**Comment by Bakser** [comment]
您好，这是因为NA标签代表的是“不是事件”，而不是一个定义良好的语义类。它跟其他的标签是不同的，比如说将一个NA数据成功预测为一个NA数据是不算在true positive结果里的，因此这里loss采用的是错误分类为其他类别的概率平均数。

**Comment by hlee-top** [comment]
作者您好，是否可以认为对不可信集合中的NA事件，如果标注为NA，其实标注结果应该是正确的，因此计算Generator的loss时采用其他事件的平均值。

**Comment by Bakser** [comment]
您好，没有明白什么叫做“其实标注结果应该是正确的”？
我再详细解释一下，如果我们把NA当作一个与其他类别一样的标签来计算，训练目标（最大化分类为NA的概率）会要求所有NA的数据的表示向量与NA这个类别的表示向量相近。但这是不合理的，因为NA的数据并没有共性，没有一致的语义。而别的类别是有一致的语义的，比如所有Attack类型的数据都表达了攻击事件的发生。因此这里的训练目标是“最小化分类为正常类别的概率”，即只要求它们跟正常类别的数据表示相远即可，不要求NA数据之间互相相似。

**Comment by hlee-top** [comment]
哦哦，明白了，感谢您的回复！

**Comment by Macvh** [comment]
您好，那公式9右边不是为1的平均数吗，分类为NA的概率是1除（标签数-1）吗
