### ISSUE TITLE
关于数据划分

### ISSUE THREAD

**Issue by xixy** [thunlp/Adv-ED#12]
您好，请问您论文中使用的数据划分是什么样子的呢？是否与HMEAE工作中的数据划分保持一致(https://github.com/thunlp/HMEAE/blob/master/logs/split.json )？谢谢

**Comment by Bakser** [comment]
您好，是的。

**Comment by Bakser** [comment]
您好，最近[另一个issue](https://github.com/THU-KEG/MAVEN-dataset/issues/4#issuecomment-910101742)使我们注意到之前HMEAE仓库logs文件夹下上传的split文件内容有误。请以主文件夹下的split文件以及现在更新过的[split.json](https://github.com/thunlp/HMEAE/blob/master/logs/split.json)为准。抱歉给您带来困扰。
