### ISSUE TITLE
关于论文中Generator的一些问题请教

### ISSUE THREAD

**Issue by carrie0307** [thunlp/Adv-ED#3]
您好，关于论文想请教您一个问题，希望能得到您赐教：
 
请问文中的Generator选择出困惑度高的实例(selecting the most confusing instances from U to cheat the discriminator)的目的是什么？是为了增强对D的训练(是否能理解为:将G选出的实例作为负例促进D的训练？), 还是理解为过滤掉noisy data减少对D的干扰呢?如果在您的整个系统架构中去掉G, 会有什么影响呢？

初入Event Detection领域，冒昧之处请见谅。期待您的回答，谢谢！

**Comment by Bakser** [comment]
应当理解为前一种，二者的adversarial training其实是一个互相促进的过程。如果去掉G就和普通的没有特别优化噪声场景适应能力的ED模型架构完全一样了。
