### ISSUE TITLE
DMCNN

### ISSUE THREAD

**Issue by shiqing1234** [thunlp/Adv-ED#6]
DMCNN是说根据trigger的位置动态的将句子划分成两部分，并通过concat，cnn，进行trigger的分类，那trigger识别是怎么做出来的那？

**Comment by Bakser** [comment]
对于DMCNN等Neural方法，通常的做法是不分开做分类和识别，而是在分类时加入一类Negative或者说N/A类，直接做34分类，分类到N/A的即是负例。
