### ISSUE TITLE
关于远程监督方面的问题

### ISSUE THREAD

**Issue by PengShi27** [thunlp/Adv-ED#8]
您好，请问一下对于Distant Supervision场景时，使用什么做测试集呢？

**Comment by Bakser** [comment]
您好，抱歉之前没看到这条issue。我们Distant Supervision场景使用的数据集来自[Automatically Labeled Data Generation for Large Scale Event Extraction](https://aclanthology.org/P17-1038/)这篇论文，可以在https://github.com/acl2017submission/event-data 下载。我们按照event_instance.csv随机划分了20%的Freebase instance作为测试集，以及10%的instance作为验证集。
