### ISSUE TITLE
如何划分`TrainA_conf`和`TrainA_unconf`

### ISSUE THREAD

**Issue by Riroaki** [thunlp/Adv-ED#9]
请问是训练和验证的区别吗？

**Comment by Bakser** [comment]
您好，非常抱歉之前没注意到issue。这里的_conf即是文章中的reliable set，_unconf即是文章中的unreliable set。如何划分可以参考[论文](https://aclanthology.org/N19-1105.pdf)第3.4节中的介绍，两种场景下不太一样。简单来说在semi-supervised场景下我们将人工标注数据设为reliable set，自动扩增的数据设为unreliable set；在distant supervision场景下我们按照模型的confidence划分reliable set和unreliable set。
